data_url: 'http://kdd.ics.uci.edu/databases/kddcup99/kddcup.data.gz'
attack_types_url: 'http://kdd.ics.uci.edu/databases/kddcup99/training_attack_types'
compressed_path: 'kddcup.data.gz'
model_filename: 'intruder-model1.pkl'
model_s3_key: 'demo/model_s3_key'
full_data_s3_key: 'demo/kdd.data'
full_data_filename: 'kdd.data'
quick_data_s3_key: 'demo/intruder-training.csv'
quick_data_filename: 'intruder-training.csv'
df_columns: 
    - 'duration'
    - 'protocol_type'
    - 'service'
    - 'flag'
    - 'src_bytes'
    - 'dst_bytes'
    - 'land'
    - 'wrong_fragment'
    - 'urgent'
    - 'hot'
    - 'num_failed_logins'
    - 'logged_in'
    - 'num_compromised'
    - 'root_shell'
    - 'su_attempted'
    - 'num_root'
    - 'num_file_creations'
    - 'num_shells'
    - 'num_access_files'
    - 'num_outbound_cmds'
    - 'is_host_login'
    - 'is_guest_login'
    - 'count'
    - 'srv_count'
    - 'serror_rate'
    - 'srv_serror_rate'
    - 'rerror_rate'
    - 'srv_rerror_rate'
    - 'same_srv_rate'
    - 'diff_srv_rate'
    - 'srv_diff_host_rate'
    - 'dst_host_count'
    - 'dst_host_srv_count'
    - 'dst_host_same_srv_rate'
    - 'dst_host_diff_srv_rate'
    - 'dst_host_same_src_port_rate' 
    - 'dst_host_srv_diff_host_rate'
    - 'dst_host_serror_rate'
    - 'dst_host_srv_serror_rate'
    - 'dst_host_rerror_rate'
    - 'dst_host_srv_rerror_rate'
    - 'class'
    
basic_columns:
    - 'duration'
    - 'src_bytes'
    - 'dst_bytes'
    - 'land'
    - 'wrong_fragment'
    - 'urgent'

content_columns:
    - 'hot'
    - 'num_failed_logins'
    - 'logged_in'
    - 'num_compromised'
    - 'root_shell'
    - 'su_attempted'
    - 'num_root'
    - 'num_file_creations'
    - 'num_shells'
    - 'num_access_files'
    - 'num_outbound_cmds'
    - 'is_host_login'
    - 'is_guest_login'

traffic_columns:
    - 'count'
    - 'serror_rate'
    - 'rerror_rate'
    - 'same_srv_rate'
    - 'diff_srv_rate'
    - 'srv_count'
    - 'srv_serror_rate'
    - 'srv_rerror_rate'
    - 'srv_diff_host_rate'
    
classmap:    
    - normal: 0
    - dos: 1
    - probe: 2
    - u2r: 3
    - r2l: 4

features: 
    - 'count'
    - 'serror_rate'
    - 'rerror_rate'
    - 'same_srv_rate'
    - 'diff_srv_rate'
    - 'srv_count'
    - 'srv_serror_rate'
    - 'srv_rerror_rate'
    - 'srv_diff_host_rate'
    - 'hot'
    - 'num_failed_logins'
    - 'logged_in'
    - 'num_compromised'
    - 'root_shell'
    - 'su_attempted'
    - 'num_root'
    - 'num_file_creations'
    - 'num_shells'
    - 'num_access_files'
    - 'num_outbound_cmds'
    - 'is_host_login'
    - 'is_guest_login'
    - 'duration'
    - 'src_bytes'
    - 'dst_bytes'
    - 'land'
    - 'wrong_fragment'
    - 'urgent'
    - 'is_service_other'
    - 'is_flag_REJ'
    - 'src_dst_ratio'
    - 'is_service_FTP'
    - 'is_flag_RSTR'
    - 'is_service_private'
    - 'is_flag_S0'
    - 'is_service_eco_i'
    